### PR TITLE
[Leia] fix crash and freeze problem from wrong file seek

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by babayaga40** [comment]
is this also based on the kodi log i sent you, or is the random quitting of a movie a another problem thtat needs solving?

**Comment by AlwinEsch** [comment]
Not 100% sure, but this can also relate to them by seek as his position can be not correct.

**Comment by AlwinEsch** [comment]
Maybe you can test the play with from here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/1/artifacts

**Comment by babayaga40** [comment]
> Maybe you can test the play with from here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/1/artifacts

Tested now, and still have the problem that it randomly stops playing, so not the same fault :/

**Comment by fritsch** [comment]
If you use a Shield and SMB on Android, then please open your own ticket.

**Comment by babayaga40** [comment]
> If you use a Shield and SMB on Android, then please open your own ticket.

Thanks, done :)

**Pull request merged**
